### ISSUE TITLE
输入sessionId之后报错！！！！！

### ISSUE THREAD

**Issue by JJdog** [Mocha-L/wechat_wegoing#4]
score_with_salt: wx7a727ff7d940bb3f_newscore:232800_level:334_baoshi:233_combo:233
result: 7746857
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "D:\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1716, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1456, in _raise_ssl_error
    _raise_current_error()
  File "D:\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "D:\Anaconda3\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "D:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='game.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/gametetrisws/syncgame?session_id=rXH000000000000000GZew@oUrsf0aVM01XfwBTAbA3XE9yfJRw (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 84, in <module>
    main()
  File "run.py", line 73, in main
    headers = headers
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='game.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/gametetrisws/syncgame?session_id=rXH00000000000000030GZew@oUrsf0aVM01XfwBTAbA3XE9yfJRw (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by cjy9492** [comment]
run.py中session.post加一个参数verify=False，改成这样就不报错了。
req = session.post(
        'https://game.weixin.qq.com/cgi-bin/gametetrisws/syncgame?session_id={}'.format(sessionid),
        data=json.dumps(data),
        headers = headers,verify=False
    ).json()

**Comment by Mocha-L** [comment]
@JJdog @cjy9492 说的是对的
或者你把抓包工具关掉，再运行代码就可以啦
